apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTaskTemplate
metadata:
  name: alaudaTestResult
  annotations:
    alauda.io/displayName.zh-CN: 测试结果
    alauda.io/displayName.en: TestResult
    alauda.io/description.zh-CN: 测试结果
    alauda.io/description.en: TestResult
    alauda.io/readme.zh-CN: 测试结果
    alauda.io/readme.en: TestResult
    alauda.io/version: v0.1
  labels:
    catgory: Test
spec:
  engine: gotpl
  body: |+
      {{- if .analysisReport}}
        junit '{{.testResultXml}}'
      {{- else}}
       echo "No Result Analysis"
      {{- end}}
  arguments:
    - name: "analysisReport"
      schema:
        type: boolean
      display:
        type: boolean
        name:
          zh-CN: "是否解析测试报告"
          en: "Enable If Wait QualityGate Result"
        description:
          zh-CN: "如果开启，当前将会对测试报告进行解析"
          en: "If Enable, Will Analysis Test Result "
      required: false
    - name: "testResultXml"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "报告存放目录"
          en: "The location of the test result"
      required: true
      relation:
        - action: show
          when:
            name: analysisReport
            value: true
