apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: alaudaTestResult
  annotations:
    alauda.io/displayName.zh-CN: 生成测试报告
    alauda.io/displayName.en: test result
    alauda.io/description.zh-CN: 生成测试报告
    alauda.io/description.en: test result
    alauda.io/readme.zh-CN: 生成测试报告
    alauda.io/readme.en: test result
    alauda.io/version: v0.2.1
    alauda.io/style.icon: updateService
  labels:
    category: Test
spec:
  engine: graph
  withSCM: true
  options:
    timeout: 5400
  stages:
    - name: Clone      
      tasks:
        - name: Clone
          type: public/clone
    - name: TestResult
      tasks:
        - name: TestResult
          type: zpyu/alaudaTestResult
          options:
            timeout: 3600
  arguments:
    - displayName:
        zh-CN: "基本信息"
        en: "Basic Info"
      items:
        - name: "maventest"
          schema:
            type: string
          binding:
            - alaudamaventest.args.maventest
          display:
            type: string
            name:
              zh-CN: "maven测试"
              en: "maven test"
            description:
              zh-CN: maven测试
              en: Path of ci command executing
          required: true  
        - name: "analysisReport"
          schema:
            type: boolean
          binding:
            - TestResult.args.analysisReport
          display:
            type: boolean
            name:
              zh-CN: "是否解析报告"
              en: "analysis the report"
            description:
              zh-CN: "是否解析报告"
              en: "analysis the report"
          required: true
        - name: "testResultXml"
          schema:
            type: string
          binding:
            - TestResult.args.testResultXml
          display:
            type: string
            name:
              zh-CN: "test result xml 位置"
              en: "test result "
            description:
              zh-CN: "XML 位置"
              en: the location of xml
          required: true
          relation:
            - action: show
              when:
                name: analysisReport
                value: true
