apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: alaudaTestResult
  annotations:
    alauda.io/displayName.zh-CN: 生成测试报告
    alauda.io/displayName.en: test result
    alauda.io/description.zh-CN: 生成测试报告
    alauda.io/description.en: test result
    alauda.io/readme.zh-CN: 生成测试报告
    alauda.io/readme.en: test result
    alauda.io/version: v0.2.9
    alauda.io/style.icon: updateService
  labels:
    category: Test
spec:
  engine: graph
  withSCM: true
  options:
    timeout: 5400
  stages:
    - name: Clone      
      tasks:
        - name: Clone
          type: testorg001/clone
    - name: maventeset
      tasks:
        - name: maventeset
          type: testorg001/alaudamaventest
  arguments:
    - displayName:
        zh-CN: "基本信息"
        en: "Basic Info"
      items:
        - name: "testResultXml"
          schema:
            type: string
          binding:
            - maventeset.args.testResultXml
          display:
            type: string
            name:
              zh-CN: "test result xml 位置"
              en: "test result "
            description:
              zh-CN: "XML 位置"
              en: the location of xml
      required: true

